spring:
  config:
    activate:
      on-profile: local

tcp:
  client:
    port:
      host: localhost
      stockA:
        index: 22903
  server:
    port:
      host: localhost
      stockA:
        index: 22903
