version: '3.8'
services:
  mysql:
    image: 'mysql:5.7'
    ports:
      - '7777:3306'
    hostname: mysql
    container_name: pig-mysql
    volumes:
      - ./docker-init-sql/create-db.sql:/docker-entrypoint-initdb.d/create-db.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: 'Asia/Seoul'
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    networks:
      - mysqlnetwork
  redis:
    image: 'redis:alpine'
    hostname: redis
    container_name: pig-redis
    ports:
      - '6666:6379'
    networks:
      - mysqlnetwork

volumes:
  mysql:
    driver: local
  redis:
    driver: local

networks:
  mysqlnetwork:
    driver: bridge